---
name: "Create PR"
description: 'Commit and create PR'

inputs:
  base:
    description: 'Base branch to create PR against'
    required: true
    default: 'main'
  token:
    description: 'PAT for creating PR'
    required: true
  add-paths:
    description: 'Paths to add to commit'
    required: false
    default: '.'
  commit-message:
    description: 'Commit message'
    required: false
    default: 'Automated commit'
  pr-title:
    description: 'PR title'
    required: false
    default: 'Automated PR'
  pr-body:
    description: 'PR body'
    required: false
    default: 'Automated PR'
  pr-condition-cmd:
    description: 'Command to check if PR should be created'
    required: false
    default: git status --porcelain


runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.name "Forgejo Bot"
        git config --global user.email "forgejo@users.noreply.git.araj.me"
      shell: bash
      name: "Configure git"
    - name: "Pre-setup"
      run: |
        git fetch --all
        git checkout -b automated-pr-change
      shell: bash
    - name: "Commit and create PR"
      shell: bash
      run: |
        if [[ -n "$(${{ inputs.pr-condition-cmd }})" ]]; then
          git add ${{ inputs.add-paths }}
          git commit -m ${{ inputs.commit-message }}
          git push --force-with-lease origin automated-pr-change
          curl -X 'POST' \
          'https://git.araj.me/api/v1/repos/maxking/dns-utils/pulls' \
          -H 'accept: application/json' \
          -H 'Authorization: token ${{ inputs.token }}' \
          -H 'Content-Type: application/json' \
          -d '{
          "assignee": "maxking",
          "base": "${{ inputs.base }}",
          "body": "${{ inputs.pr-body }}",
          "head": "automated-pr-change",
          "title": "${{ inputs.pr-title }}"
          }'
        else
          echo "No changes to commit"
        fi
